version: '2.1'
services:
  buildbox:
    build: buildbox
    restart: unless-stopped
    volumes:
      - ..:/home/developer/mtc
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DEV_UID
      - DEV_GID
      - DOCKER_GID